### Second Iter (05 May)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_df =  pd.read_csv('data/train.csv', index_col='PassengerId')
train_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

First Iteration Preprocessing

In [3]:
from pipeline.feature_preprocessing import preprocess

df = preprocess(train_df)
df

             Pclass  SibSp     Parch       Age      Fare  Survived  is_female  \
PassengerId
1               1.0    0.2  0.000000 -0.527669 -0.516380         0          0
2               0.0    0.2  0.000000  0.577094  0.694046         1          1
3               1.0    0.0  0.000000 -0.251478 -0.503620         1          1
4               0.0    0.2  0.000000  0.369951  0.350326         1          1
5               1.0    0.0  0.000000  0.369951 -0.501257         0          0
...             ...    ...       ...       ...       ...       ...        ...
886             1.0    0.0  0.833333  0.646142 -0.102875         0          1
887             0.5    0.0  0.000000 -0.182430 -0.407687         0          0
888             0.0    0.0  0.000000 -0.734812 -0.086335         1          1
890             0.0    0.0  0.000000 -0.251478 -0.086335         1          0
891             1.0    0.0  0.000000  0.162808 -0.506928         0          0

             Embarked_C  Embarked_S
PassengerId
1                   0.0         1.0
2                   1.0         0.0
3                   0.0         1.0
4                   0.0         1.0
5                   0.0         1.0
...                 ...         ...
886                 0.0         0.0
887                 0.0         1.0
888                 0.0         1.0
890                 1.0         0.0
891                 0.0         0.0

[712 rows x 9 columns]

,Pclass,SibSp,Parch,Age,Fare,Survived,is_female,Embarked_C,Embarked_S
PassengerId,,,,,,,,,
1,1.0,0.2,0.000000,-0.527669,-0.516380,0,0,0.0,1.0
2,0.0,0.2,0.000000,0.577094,0.694046,1,1,1.0,0.0
3,1.0,0.0,0.000000,-0.251478,-0.503620,1,1,0.0,1.0
4,0.0,0.2,0.000000,0.369951,0.350326,1,1,0.0,1.0
5,1.0,0.0,0.000000,0.369951,-0.501257,0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
886,1.0,0.0,0.833333,0.646142,-0.102875,0,1,0.0,0.0
887,0.5,0.0,0.000000,-0.182430,-0.407687,0,0,0.0,1.0
888,0.0,0.0,0.000000,-0.734812,-0.086335,1,1,0.0,1.0
890,0.0,0.0,0.000000,-0.251478,-0.086335,1,0,1.0,0.0
891,1.0,0.0,0.000000,0.162808,-0.506928,0,0,0.0,0.0

In [8]:
y = df.Survived
X = df.drop(columns=['Survived'])
np_X = X.to_numpy()
np_y = y.to_numpy()

print(f'{np_X.shape=}, {np_y.shape=}')

np_X.shape=(712, 8), np_y.shape=(712,)

In [11]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error, accuracy_score

n_splits = 5

kf = KFold(n_splits=n_splits)
losses = np.ndarray(n_splits)
accuracy_list = np.ndarray(n_splits)

In [12]:
for i, (train_index, test_index) in enumerate(kf.split(np_X)):
    lr = RidgeClassifier()

    fitted = lr.fit(np_X[train_index], np_y[train_index])

    y_pred = fitted.predict(np_X[test_index])
    y_true = np_y[test_index]
    
    losses[i] = mean_squared_error(y_true, y_pred)
    accuracy_list[i] = accuracy_score(y_true, y_pred)

print(f'{losses=}, {losses.mean()=}')
print(f'{accuracy_list=}, {accuracy_list.mean()=}')

losses=array([0.21678322, 0.20979021, 0.24647887, 0.26056338, 0.19014085]), losses.mean()=np.float64(0.22475130503299517)
accuracy_list=array([0.78321678, 0.79020979, 0.75352113, 0.73943662, 0.80985915]), accuracy_list.mean()=np.float64(0.7752486949670049)