### main.py через jupyter

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from config import config
from utils import set_seed

In [2]:
set_seed(config.general.seed)

In [3]:
full_df = pd.read_csv(config.paths.train, index_col='PassengerId')
full_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    full_df, 
    test_size=config.split.test_size,
    random_state=config.general.seed, 
    shuffle=config.split.shuffle
)

First Iteration Preprocessing

In [5]:
from preprocessing import preprocess

df = preprocess(train_df)
df.describe()

,Survived,Pclass,Age,SibSp,Parch,Fare,is_female,Embarked_C,Embarked_S,Family_Size,Alone
count,712.000000,712.000000,712.000000,712.000000,712.000000,712.000000,712.000000,712.000000,712.000000,712.000000,712.000000
mean,0.376404,2.330056,29.612837,0.553371,0.379213,32.586276,0.344101,0.175562,0.740169,0.932584,0.602528
std,0.484824,0.824584,13.216134,1.176404,0.791669,51.969529,0.475408,0.380714,0.438850,1.682525,0.489719
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,22.000000,0.000000,0.000000,7.925000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,3.000000,30.000000,0.000000,0.000000,14.454200,0.000000,0.000000,1.000000,0.000000,1.000000
75%,1.000000,3.000000,36.000000,1.000000,0.000000,30.500000,1.000000,0.000000,1.000000,1.000000,1.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000,1.000000,1.000000,10.000000,1.000000

In [6]:
from linear import Linear

# logreg
linear = Linear(df, model='logreg')

linear.cv()

(array([0.81118881, 0.76923077, 0.78169014, 0.83802817, 0.78169014]),
 np.float64(0.7963656062247612))

In [7]:
ridge = Linear(df, model='ridge')

ridge.cv()

(array([0.7972028 , 0.75524476, 0.77464789, 0.84507042, 0.79577465]),
 np.float64(0.7935881020388063))