### main.py через jupyter

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from ml_pipeline.config import config
from ml_pipeline.utils import set_seed

In [2]:
set_seed(config.general.seed)

xd

In [3]:
full_df = pd.read_csv(config.paths.train, index_col='PassengerId')
full_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    full_df, 
    test_size=config.split.test_size,
    random_state=config.general.seed, 
    shuffle=config.split.shuffle
)

First Iteration Preprocessing

In [5]:
from ml_pipeline.preprocessing import preprocess

df = preprocess(train_df)
df
# df.describe()

,Survived,Pclass,Sex,SibSp,Parch,Family_Size,Alone,Embarked_C,Embarked_S,Age_Group,Fare_Range
PassengerId,,,,,,,,,,,
332,0,1,0,0,0,0,1,0.0,1.0,2,2
734,0,2,0,0,0,0,1,0.0,1.0,1,1
383,0,3,0,0,0,0,1,0.0,1.0,1,0
705,0,3,0,1,0,1,0,0.0,1.0,1,0
814,0,3,1,4,2,6,0,0.0,1.0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
107,1,3,1,0,0,0,1,0.0,1.0,1,0
271,0,1,0,0,0,0,1,0.0,1.0,2,3
861,0,3,0,2,0,2,0,0.0,1.0,2,1
436,1,1,1,1,2,3,0,0.0,1.0,0,3
103,0,1,0,0,1,1,0,0.0,1.0,1,3

In [6]:
from ml_pipeline.linear import Linear

# logreg
linear = Linear(df, penalty='l2')

linear.cv()

(array([0.81818182, 0.76223776, 0.76056338, 0.85211268, 0.76760563]),
 np.float64(0.7921402541120851))

In [7]:
logreg_l1 = Linear(df, penalty='l1')

logreg_l1.cv()

(array([0.81818182, 0.76923077, 0.75352113, 0.84507042, 0.76760563]),
 np.float64(0.7907219541022359))

In [8]:
logreg_e = Linear(df, penalty='elastic', elastic_l1_ratio=0.8)

logreg_e.cv()

(array([0.81818182, 0.76223776, 0.76056338, 0.84507042, 0.76760563]),
 np.float64(0.7907318034078598))